preset support

diff --git a/archer b/archer
--- a/archer
+++ b/archer
@@ -239,7 +239,7 @@ install_pacman_packages() {
         $([ "$has_battery" = yes ] && echo tlp)
         $([ "$has_battery" = yes ] && [ "$has_wireless" = yes ] && echo tlp-rdw)
 
-	acpi
+        acpi
         #TODO: condition for acpilight
         acpilight
 
@@ -252,6 +252,7 @@ install_pacman_packages() {
     	wget
     	htop
         xwallpaper
+        qutebrowser
     	alsa-utils
         arc-gtk-theme
     )
@@ -268,9 +269,8 @@ install_pacman_packages() {
 
 install_aur_packages() {
     local packages=(
-        brave-bin
-        xcursor-breeze
-        nerd-fonts-hack
+        nerd-fonts-fira-code
+        drive-bin
     )
 
     for package in ${packages[@]}; do echo [DEBUG]: AUR package: =$package= >> archer.log; done
@@ -408,52 +408,74 @@ create_user() {
 }
 
 #TODO: progress bar
+#TODO: mirror ranking
 setup() {
-    echo [LOG] > archer.log
+    echo "[LOG]" > archer.log
 
     set_colorscheme
 
     set_dialogrc
 
     boot_mode="$(detect_boot_mode)"
-    echo [DEBUG]: boot mode: =$boot_mode= >> archer.log
+    echo "[DEBUG]: boot mode: =$boot_mode=" >> archer.log
 
-    [ "$boot_mode" != UEFI ] && echo [ERROR]: boot mode not supported: =$boot_mode= >> archer.log
+    [ $boot_mode != UEFI ] && echo "[ERROR]: boot mode not supported: =$boot_mode=" >> archer.log
+    [ $boot_mode != UEFI ] && exit 0
 
     cpu_vendor="$(detect_cpu_vendor)"
-    echo [DEBUG]: cpu vendor: =$cpu_vendor= >> archer.log
+    echo "[DEBUG]: cpu vendor: =$cpu_vendor=" >> archer.log
     gpu_configuration="$(detect_gpu_configuration)"
-    echo [DEBUG]: gpu configuration: =$gpu_configuration= >> archer.log
+    echo "[DEBUG]: gpu configuration: =$gpu_configuration=" >> archer.log
     has_battery="$(detect_battery)"
-    echo [DEBUG]: battery: =$has_battery= >> archer.log
+    echo "[DEBUG]: battery: =$has_battery=" >> archer.log
     has_wireless="$(detect_wireless)"
-    echo [DEBUG]: wireless: =$has_wireless= >> archer.log
+    echo "[DEBUG]: wireless: =$has_wireless=" >> archer.log
     has_touchpad="$(detect_touchpad)"
-    echo [DEBUG]: touchpad: =$has_touchpad= >> archer.log
+    echo "[DEBUG]: touchpad: =$has_touchpad=" >> archer.log
     has_ssd="$(detect_ssd)"
-    echo [DEBUG]: ssd: =$has_ssd= >> archer.log
-    selected_drive="$(get_drive)"
-    echo [DEBUG]: selected drve: =$selected_drive= >> archer.log
-    mirrorlist_country="$(get_mirrorlist_country)"
-    echo [DEBUG]: mirrorlist country: =$mirrorlist_country= >> archer.log
-    locale="$(get_locale)"
-    echo [DEBUG]: locale: =$locale= >> archer.log
-    keymap="$(get_keymap)"
-    echo [DEBUG]: keymap: =$keymap= >> archer.log
-    timezone="$(get_timezone)"
-    echo [DEBUG]: timezone: =$timezone= >> archer.log
-    hostname="$(get_hostname)"
-    echo [DEBUG]: hostname: =$hostname= >> archer.log
-    username="$(get_username)"
-    echo [DEBUG]: username: =$username= >> archer.log
-    password="$(get_password)"
-    echo [DEBUG]: password: =$password= >> archer.log
+    echo "[DEBUG]: ssd: =$has_ssd=" >> archer.log
+
+    if [ "$preset" = roliboy ]; then
+        selected_drive="$(get_drive)"
+        echo "[DEBUG]: selected drve: =$selected_drive=" >> archer.log
+        mirrorlist_country="RO"
+        echo "[DEBUG]: mirrorlist country: =$mirrorlist_country=" >> archer.log
+        locale="en_US.UTF-8"
+        echo "[DEBUG]: locale: =$locale=" >> archer.log
+        keymap="us.map.gz"
+        echo "[DEBUG]: keymap: =$keymap=" >> archer.log
+        timezone="Europe/Bucharest"
+        echo "[DEBUG]: timezone: =$timezone=" >> archer.log
+        hostname="arch"
+        echo "[DEBUG]: hostname: =$hostname=" >> archer.log
+        username="roliboy"
+        echo "[DEBUG]: username: =$username=" >> archer.log
+        password="$(get_password)"
+        echo "[DEBUG]: password: =$password=" >> archer.log
+    else
+        selected_drive="$(get_drive)"
+        echo "[DEBUG]: selected drve: =$selected_drive=" >> archer.log
+        mirrorlist_country="$(get_mirrorlist_country)"
+        echo "[DEBUG]: mirrorlist country: =$mirrorlist_country=" >> archer.log
+        locale="$(get_locale)"
+        echo "[DEBUG]: locale: =$locale=" >> archer.log
+        keymap="$(get_keymap)"
+        echo "[DEBUG]: keymap: =$keymap=" >> archer.log
+        timezone="$(get_timezone)"
+        echo "[DEBUG]: timezone: =$timezone=" >> archer.log
+        hostname="$(get_hostname)"
+        echo "[DEBUG]: hostname: =$hostname=" >> archer.log
+        username="$(get_username)"
+        echo "[DEBUG]: username: =$username=" >> archer.log
+        password="$(get_password)"
+        echo "[DEBUG]: password: =$password=" >> archer.log
+    fi
 
 
     create_partitions
 
     enable_ntp
-    echo [DEBUG]: network time protocol: =$(timedatectl show | grep '^NTP=' | cut -d'=' -f 2)= >> archer.log
+    echo "[DEBUG]: network time protocol: =$(timedatectl show | grep '^NTP=' | cut -d'=' -f 2)=" >> archer.log
 
     download_mirrorlist
     awk '/Server/ {print "[DEBUG]: mirror:", "="$3"="}' /etc/pacman.d/mirrorlist >> archer.log
@@ -461,41 +483,41 @@ setup() {
     install_pacman_packages
 
     install_aur_packages
-    echo [DEBUG]: aur packages installed: =$(arch-chroot /mnt /bin/bash <<< 'pacman -Qm | wc -l')= >> archer.log
+    echo "[DEBUG]: aur packages installed: =$(arch-chroot /mnt /bin/bash <<< 'pacman -Qm | wc -l')=" >> archer.log
 
     generate_fstab
-    echo [DEBUG]: fstab generated: =$([ -n "$(grep noatime /mnt/etc/fstab)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: fstab generated: =$([ -n "$(grep noatime /mnt/etc/fstab)" ] && echo yes || echo no)=" >> archer.log
 
     generate_locale
-    echo [DEBUG]: locale generated: =$([ -n "$(grep $locale /mnt/etc/locale.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: locale generated: =$([ -n "$(grep $locale /mnt/etc/locale.conf)" ] && echo yes || echo no)=" >> archer.log
 
     set_keymap
-    echo [DEBUG]: keymap set: =$([ -n "$(grep $keymap /mnt/etc/vconsole.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: keymap set: =$([ -n "$(grep $keymap /mnt/etc/vconsole.conf)" ] && echo yes || echo no)=" >> archer.log
 
     install_bootloader
-    echo [DEBUG]: bootloader installed: =$([ -n "$(grep UUID /mnt/boot/loader/entries/arch.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: bootloader installed: =$([ -n "$(grep UUID /mnt/boot/loader/entries/arch.conf)" ] && echo yes || echo no)=" >> archer.log
 
     set_timezone
-    echo [DEBUG]: timezone configured: =$([ -n "$(ls -la /mnt/etc/localtime | grep $timezone)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: timezone configured: =$([ -n "$(ls -la /mnt/etc/localtime | grep $timezone)" ] && echo yes || echo no)=" >> archer.log
 
     configure_network
-    echo [DEBUG]: network configured: =$([ -n "$(grep $hostname /mnt/etc/hosts)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: network configured: =$([ -n "$(grep $hostname /mnt/etc/hosts)" ] && echo yes || echo no)=" >> archer.log
 
     configure_pacman
-    echo [DEBUG]: pacman configured: =$([ -n "$(grep ILoveCandy /mnt/etc/pacman.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: pacman configured: =$([ -n "$(grep ILoveCandy /mnt/etc/pacman.conf)" ] && echo yes || echo no)=" >> archer.log
 
     [ "$has_touchpad" = yes ] && configure_libinput
-    echo [DEBUG]: libinput configured: =$([ -n "$(grep InputClass /mnt/etc/X11/xorg.conf.d/50-touchpad.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: libinput configured: =$([ -n "$(grep InputClass /mnt/etc/X11/xorg.conf.d/50-touchpad.conf)" ] && echo yes || echo no)=" >> archer.log
 
     [ "$has_battery" = yes ] && configure_tlp
     # TODO: update this after tlp config will be migrated to main file
-    echo [DEBUG]: tlp configured: =$([ -n "$(grep nvidia /mnt/etc/tlp.d/10-driver-blacklist.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: tlp configured: =$([ -n "$(grep nvidia /mnt/etc/tlp.d/10-driver-blacklist.conf)" ] && echo yes || echo no)=" >> archer.log
 
     configure_journald
-    echo [DEBUG]: journald configured: =$([ -n "$(grep '^SystemMaxUse' /mnt/etc/systemd/journald.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: journald configured: =$([ -n "$(grep '^SystemMaxUse' /mnt/etc/systemd/journald.conf)" ] && echo yes || echo no)=" >> archer.log
 
     configure_coredump
-    echo [DEBUG]: coredump configured: =$([ -n "$(grep '^Storage' /mnt/etc/systemd/coredump.conf)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: coredump configured: =$([ -n "$(grep '^Storage' /mnt/etc/systemd/coredump.conf)" ] && echo yes || echo no)=" >> archer.log
 
     enable_services
     #systemctl status
@@ -504,7 +526,7 @@ setup() {
     #sudo check
 
     create_user
-    echo [DEBUG]: user created: =$([ -n "$(grep $username <<< `arch-chroot /mnt /bin/bash <<< 'cut -d: -f1 /etc/passwd'`)" ] && echo yes || echo no)= >> archer.log
+    echo "[DEBUG]: user created: =$([ -n "$(grep $username <<< `arch-chroot /mnt /bin/bash <<< 'cut -d: -f1 /etc/passwd'`)" ] && echo yes || echo no)=" >> archer.log
 }
 
 setup
